// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prgjfbrcobbbkkeieplq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZ2pmYnJjb2JiYmtrZWllcGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjM1MjEsImV4cCI6MjA2MDI5OTUyMX0.NnpX5dFTydnfJer8RfikhC0GIAxeNsIzhX63SSZ5Zwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);